### ISSUE TITLE
BUG! Play/Pause button on optimization file reading not working as expected 

### ISSUE THREAD

**Issue by alexpsnchz** [chdominguez/Atomic#23]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

The **Play/Pause** button does not work properly. When clicking on it to visualize the different steps of the optimization, the button continues to appear in **Play**, and not in **Pause** as it should appear to be able to click and stop the visualization

### Expected behaviour

The bug fixed should cause the Pause button to appear when the optimization visual is playing.

### Steps to reproduce

1. Open a log file (in my case Gaussian log file) 
2. Click Play bottom-right button
3. See how it does not change to Pause during the visualization

### Version

```markdown
- OS: MacOS 12.5 
- Atomic: 0.4
```

### Supporting information

Picture of the button to be fixed

<img width="82" alt="Captura de Pantalla 2022-09-01 a las 12 32 34" src="https://user-images.githubusercontent.com/100805236/187893892-2fbc0347-7853-43cf-b188-b2351a430ab2.png">

**Comment by chdominguez** [comment]
Fixed for future releases.
