### ISSUE TITLE
[BUG] Error representing a protein structure

### ISSUE THREAD

**Issue by alexpsnchz** [chdominguez/Atomic#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

I just open a pdb structure of a protein structure and Atomic visualizer didn't show it in the correct way. All atoms appear in a plane (as seen in the attached screenshot in the the Supporting information). 

After it, when trying to represent it with Cartoon appearance, the visualizer didn't show anything. 

### Expected behaviour

I think it could come from a bad reading of the pdb file, or something similar. I attached also in the Supporting information the pdb (.zip) file to help to solve the bug. 

### Steps to reproduce

1. Open Atomic
2. Click 'Open File' bottom 
3. Select the attached file
4. Click 'Open'

### Version

```markdown
- OS: MacOS Monterey 12.6
- Atomic: 0.4.2 (2)
```

### Supporting information

<img width="1582" alt="Captura de Pantalla 2022-10-13 a las 18 54 51" src="https://user-images.githubusercontent.com/100805236/195658267-73966042-4581-413e-98b2-20eba0099aee.png">

[COX2_homodimer_wh.pdb.zip](https://github.com/chdominguez/Atomic/files/9921591/COX2_homodimer_wh.pdb.zip)

**Comment by chdominguez** [comment]
Fixed in Atomic 0.4.4. with #39
