### ISSUE TITLE
[BUG] SceneKitPlus no longer exists

### ISSUE THREAD

**Issue by JrGoodle** [chdominguez/Atomic#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

App fails to build because it can't resolve the SceneKitPlus package

### Expected behaviour

App will resolve the package and build

### Version

```markdown
- OS:
- Atomic:
```

### Supporting information

The repo no longer exists: https://github.com/chdominguez/SceneKitPlus

Was it deleted or made private?

**Comment by chdominguez** [comment]
My plan was to make public SceneKitPlus, but due to work and other projects I completely forgot. I will make it public now.

**Comment by JrGoodle** [comment]
awesome, thanks!
